[0m21:38:22.665867 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cea190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109241690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1092ad790>]}


============================== 21:38:22.668949 | 98373c2f-1415-4861-889b-b3dd0a6433e6 ==============================
[0m21:38:22.668949 [info ] [MainThread]: Running with dbt=1.6.4
[0m21:38:22.669413 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/rihadvariawa/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt_demo02', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:38:22.670122 [debug] [MainThread]: Starter project path: /Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/include/starter_project
[0m21:38:22.675831 [info ] [MainThread]: 
Your new dbt project "dbt_demo02" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:38:22.676138 [info ] [MainThread]: Setting up your profile.
[0m21:41:27.838502 [error] [MainThread]: Encountered an error:

[0m21:41:27.843269 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/task/init.py", line 308, in run
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/rihadvariawa/.pyenv/versions/3.11.2/lib/python3.11/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m21:41:27.844093 [debug] [MainThread]: Command `dbt init` failed at 21:41:27.843893 after 185.20 seconds
[0m21:41:27.844476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1091eb050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f766d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f76d10>]}
[0m21:41:27.844808 [debug] [MainThread]: Flushing usage events
